# Generated by Django 4.1.6 on 2026-01-31 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('img_src', models.URLField(blank=True, null=True)),
                ('years_of_age', models.CharField(max_length=10)),
                ('bio', models.TextField()),
                ('works', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'author',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('img_src', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField()),
                ('Author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author')),
            ],
            options={
                'db_table': 'books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='bookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='books.book')),
            ],
            options={
                'db_table': 'booksDetails',
            },
        ),
    ]
